stages:
  - test
  - release
  - deploy

run_tests:
  image: python:3.13-alpine
  stage: test
  tags:
  - custom
  script:
    - pip install uv
    - uv sync
    - uv run pytest
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

create_tag:
  image: node:latest
  stage: release
  tags:
  - custom
  script:
    - npm i @semantic-release/gitlab
    - npx semantic-release
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

create_image:
  image: docker:cli
  stage: deploy
  tags:
  - custom
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_IMAGE: $DOCKER_USER/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  script:
    - echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USER --password-stdin
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  rules:
    - if: '$CI_COMMIT_TAG'
